export class Medicine {
  'commercialName': unknown;
  'id': unknown;
  'eofCode': unknown;
  'barcode': unknown;
  'formCode': unknown;
  'inCirculation': unknown;
  'content': unknown;
  'piecesPerPackage': unknown;
  'dosePerPackage': unknown;
  'wholesalePrice': unknown;
  'retailPrice': unknown;
  'retailReducedPrice': unknown;
  'hospitalPrice': unknown;
  'withdrawn': unknown;
  'nonPrescriptable': unknown;
  'highCost': unknown;
  'executedAtIka': unknown;
  'drug': unknown;
  'desensitizationVaccine': unknown;
  'hospitalMedicine': unknown;
  'ifet': unknown;
  'atcCode': unknown;
  'specialAntibiotics': unknown;
  'doseUnit': unknown;
  'packageForm': unknown;
  'dailyDose': unknown;
  'producer': unknown;
  'medicineType': unknown;
  'referencePrice': unknown;
  'referenceReducedPrice': unknown;
  'participationPercentage': unknown;
  'medicineGroupId': unknown;
  'defaultPercentage': unknown;
  'noInn': unknown;
  'negativeList': unknown;
  'positiveList': unknown;
  'specialImport': unknown;
  'n3816': unknown;
  'executionUnit': unknown;
  'groupInfo': unknown;
  'inClusterWithGeneric': unknown;
  'clusterCode': unknown;
  'onlyByProtocol': unknown;
  'notInPharCost': unknown;
  'eopyyPreapproval': unknown;
  'ivf': unknown;
  'medicineTypeAll': unknown;
  'infoPopUp': unknown;
  'vaccine': unknown;
  'contentInternal': unknown;
  'isConsumable': unknown;
  'consumablePackQty': unknown;
  'consumableGroup': unknown;
  'isFluantiviral': unknown;
  'activeSubstance': [
    {
      'activeSubstance': {
        'id': unknown;
        'code': unknown;
        'description': unknown
      };
      'mainActiveSubstance': unknown
    }
  ];
  'updateDate': unknown;
  'insertDate': unknown;
  'typeOException': unknown;
  'defaultDosageRequired': unknown;
  'defaultDoseDaysNo': unknown;
  'defaultMedicineFrequency': unknown;
  'defaultDoseUnitNo': unknown;
  'defaultQuantityPrescribed': unknown;
  'valUnderdoseThres': unknown;
  'valOverdoseThres': unknown;
  'underdoseMessageType': unknown;
  'overdoseMessageType': unknown;
  'limitedExecution': unknown;
  'limitedExecutionUnitId': unknown;
  'onlyByProtocolAgeLimit': unknown;
  'consumableCategory': unknown;
  'drugCategoryId': unknown;
  'ePresEnabled': unknown;
}
